CREATE TABLE TB_MEDICO (
   ID_MEDICO BIGSERIAL PRIMARY KEY,
   NOME_MEDICO VARCHAR(255),
   CRM_MEDICO VARCHAR(50) UNIQUE,
   ID_ESPECIALIDADE VARCHAR(50),
   EMAIL_MEDICO VARCHAR(255) UNIQUE,
   TELEFONE_MEDICO VARCHAR(50),
   FLATIVO_MEDICO BOOLEAN,
   DT_CADASTRO TIMESTAMP
);