CREATE TABLE TB_PACIENTE (
     ID_PACIENTE BIGSERIAL PRIMARY KEY,
     NOME_PACIENTE VARCHAR(255) NOT NULL,
     CPF_PACIENTE VARCHAR(20) NOT NULL UNIQUE,
     EMAIL_PACIENTE VARCHAR(255) NOT NULL UNIQUE,
     TELEFONE_PACIENTE VARCHAR(50) NOT NULL,
     ENDERECO_PACIENTE VARCHAR(255) NOT NULL,
     DT_NASCIMENTO DATE,
     SEXO_PACIENTE VARCHAR(20),
     PLANO_PACIENTE VARCHAR(255),
     FL_ATIVO BOOLEAN,
     DT_CADASTRO TIMESTAMP
);