CREATE TABLE TB_CONSULTA (
     ID_CONSULTA BIGSERIAL PRIMARY KEY,
     DT_HORA_CONSULTA TIMESTAMP NOT NULL,
     STATUS_CONSULTA VARCHAR(50),
     OBSERVACAO VARCHAR(500),
     ID_MEDICO BIGINT NOT NULL,
     ID_PACIENTE BIGINT NOT NULL,

     CONSTRAINT FK_CONSULTA_MEDICO
         FOREIGN KEY (ID_MEDICO)
             REFERENCES TB_MEDICO(ID_MEDICO),

     CONSTRAINT FK_CONSULTA_PACIENTE
         FOREIGN KEY (ID_PACIENTE)
             REFERENCES TB_PACIENTE(ID_PACIENTE)
);
